//: intellij program arguments --spring.profiles.active=dev
info:
    app:
        description: 'Spring boot master '
        name: 'Spring boot master '
        version: 1.0.0
    company:
        name: Tomas Balaz
logging:
    file:
        name: app.log
management:
    endpoint:
        health:
            show-details: always
        info:
            enabled: true
    endpoints:
        web:
            exposure:
                include: health,info, prometheus
server:
    error:
        include-binding-errors: always
        include-message: always
        include-stacktrace: on_param
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb-dev
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-dev
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
    main:
        banner-mode: 'off'
